# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: StayWithNomads Blog
email: hello@staywithnomads.com
description: > # this means to ignore newlines until "baseurl:"
  Updates about StayWithNomads.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:4000/" # the base hostname & protocol for your site, e.g. http://example.com
main_url: "https://www.staywithnomads.com/"
# url: "https://blog.staywithnomads.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: StayWithNomads
github_username:  StayWithNomads
show_downloads: false
google_analytics: UA-99136199-1

# seo
author: StayWithNomads
twitter:
  username: StayWithNomads
logo: /assets/staywithnomads.png
social:
  name: StayWithNomads
  links:
    - https://twitter.com/StayWithNomads
    - https://www.facebook.com/StayWithNomads
    - https://plus.google.com/+StayWithNomads
    - https://github.com/StayWithNomads
# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins_dir:
  - jekyll-feed
  - kramdown
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor','.ruby-version', '.ruby-gemset', 'README.md', 'jemoji']
